feat: use prettier to organize imports
SpecterOps/BloodHound pull request #1026
Opened 2024-12-18 00:42 UTC by benwaples

## Description
Adds a plugin to prettier that sorts, combines and removes unused imports using the organizeImports feature of the TS language server.

## Motivation and Context

This PR addresses: BED-5112

Organized imports helps devs parse where code is coming from. This is particularly helpful as we replace MUI with DoodleUI and many of the components will have similar, if not the same, names to help migrate to the new component library. 

Additionally, this plugin will remove unused imports, so one less thing to review for. 

The [npm documentation](https://www.npmjs.com/package/prettier-plugin-organize-imports) is very helpful, feel free to give it a review!

## How Has This Been Tested?
confirmed that prettier will automatically update imports.

## Screenshots (optional):
n/a

## Types of changes

- Chore (a change that does not modify the application functionality)

## Checklist:

- [x] I have met the contributing prerequisites
  - Assigned myself to this PR
  - Added the appropriate labels
  - Associated an issue: https://github.com/SpecterOps/BloodHound/issues/672
  - Read the Contributing guide: https://github.com/SpecterOps/BloodHound/wiki/Contributing
- [x] I have ensured that related documentation is up-to-date
  - Open API docs
  - Code comments (GoDocs / JSDocs)
- [x] I have followed proper test practices
  - Added/updated tests to cover my changes
  - All new and existing tests passed

2025-01-07 18:29 UTC, elikmiller commented
I like the idea but I am seeing one issue.

After updating my dependencies and running `yarn format` in `cmd/ui`, `packages/javascript/js-client-library` and `packages/javascript/bh-shared/ui` I am no longer able to build the UI project and the following error appears.

```
src/main.tsx:33:16 - error TS2664: Invalid module name in augmentation, module '@mui/styles/defaultTheme' cannot be found.

33 declare module '@mui/styles/defaultTheme' {
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in src/main.tsx:33
```

2025-01-07 22:49 UTC, elikmiller requested changes
Please see my above comment!

2025-01-07 23:04 UTC, benwaples commented
@elikmiller thats sus! Ill check it out. Thanks!

2025-01-08 01:33 UTC, benwaples commented
@elikmiller found the problem! But its super weird. Its not directly related to this prettier plugin, but a side-effect from formatting the imports.

In `cmd/ui/src/App.test.tsx`, Importing `bh-shared-ui` before the src/App component caused this error. Im not entirely sure why yet, but the fix is to essentially organize the App files under an App directory such as:
```
src/
  App/
    App.tsx
    App.test.tsx
    index.ts
  main.ts // imports App
```

2025-01-08 16:32 UTC, elikmiller commented
@benwaples It looks like if we delete this module declaration in `cmd/ui/src/main.tsx` it also works.

I don't exactly remember why we needed this declaration in the first place, might have been a missed cleanup when we moved from MUI 4 to 5.

```
- declare module '@mui/styles/defaultTheme' {
-     interface DefaultTheme extends Theme {}
- }
``` #

2025-01-08 16:50 UTC, benwaples commented
@elikmiller from what I can tell it was part of the [migration from 4 -> 5](https://mui.com/material-ui/migration/v5-style-changes/?srsltid=AfmBOopA8j8gdGqOwUeS1LTrjoIngcV_Ec4f1h0gyKSNSNwmRF56l2Vj#%E2%9C%85-add-module-augmentation-for-defaulttheme-typescript) so I was hesitant to delete it. Sounds like their reasoning for the augmentation is if we use `makeStyles` or `withStyles` (which we do), but deleting the augmentation doesnt cause TS or build errors... 

If TS and the build is happy, Im happy to remove. Are you still comfortable with that?

2025-01-08 19:25 UTC, elikmiller commented
@benwaples Yes and it looks like we can remove it from `bh-shared-ui` too. I'd suggest those changes as well as checking in all the files after running `yarn format` in each project (which I know will be a huge change)

2025-01-08 21:18 UTC, benwaples commented
@elikmiller discussed offline, but to summarize, we are keeping the module augmentation in `bh-shared-ui` and believe there was a collision in module scope when loading the bh-shared-ui package before having the chance to define the augmentation in bhce.

2025-01-08 23:00 UTC, benwaples commented
@elikmiller came across more import ordering errors in `cmd/ui/src/setupTests.tsx`, `packages/javascript/bh-shared-ui/src/test-utils.jsx`, and `packages/javascript/bh-shared-ui/src/setupTests.tsx`. It appears, that the formatting is removing unused variables that are imported purposefully for either mocked or scoping reasons.

2025-01-15 00:01 UTC, merged