Create ADCS feature flag and wrap associated code
SpecterOps/BloodHound pull request #216
Opened 2023-11-15 18:19 UTC by juggernot325

## Description

This PR creates a new feature flag for enabling ADCS related endpoints, ingest logic, and post-processing logic. The feature flag is disabled by default to enable limited testing for specific scenarios. This should prevent widespread errors if there are unknown bugs in the new feature code.

A new middleware was added to allow easy addition of feature flag checking logic to any endpoint in the BloodHound API. The middleware just needs to be added to the registration of the protected endpoints, passing in the flag that controls the behavior. If the flag is disabled, a 404 will be returned to the requester.

## Motivation and Context

* This should help prevent breaking everyone's BloodHound instance if there are unknown bugs in the new ADCS code.

## How Has This Been Tested?

* Verified the feature flag is set to `enabled=false` on a fresh instance.
* Verified the ADCS endpoints are unreachable when the flag is set to `false`.
* Verified no ADCS data is ingested or post-processed when the flag is set to `false`.
* Verified the above functionality works as expected when the flag is set to `true`.

## Types of changes

-   [ ] Chore (a change that does not modify the application functionality)
-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

-   [ ] Documentation updates are needed, and have been made accordingly.
-   [ ] I have added and/or updated tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] My changes include a database migration.

2023-11-15 20:27 UTC, superlinkx commented on .github/workflows/jira-issue-transfer.yml
Lokie has already made necessary changes to this file. I'd just pull the current mainline version to avoid a potential conflict

2023-11-15 20:48 UTC, superlinkx requested changes

2023-11-16 15:26 UTC, juggernot325 commented on .github/workflows/jira-issue-transfer.yml
I'm not sure what happened here. I think it's a merge artifact. This file shouldn't have been touched.

2023-11-16 15:35 UTC, juggernot325 commented on cmd/api/src/api/middleware/middleware.go
> +
Derp, was going too fast. Good catch!

2023-11-16 17:10 UTC, superlinkx approved these changes

2023-11-16 18:18 UTC, merged