tag ag selectors on update
SpecterOps/BloodHound pull request #225
Opened 2023-11-17 03:07 UTC by irshadaj

## Description

This MR is to tag asset group selectors as soon as they are added or removed via the `api/v2/asset-groups/{id}/selectors` endpoint. This circumvents the need to wait for an analysis run to complete in order for the updated results to show.

## How Has This Been Tested?

Spun up the local environment, note the quiet period of 11 minutes:

![quiet period](https://github.com/SpecterOps/BloodHound/assets/24904109/bc590614-4708-4762-adc5-28e337fb9fb5)

Grabbed a random user from the graph database, note that this is not a T0 user:

![before](https://github.com/SpecterOps/BloodHound/assets/24904109/f0e67401-b2f5-4dbb-802d-101127f1cabe)

Added a selector for that user:

![post](https://github.com/SpecterOps/BloodHound/assets/24904109/41208163-573d-4d28-ac96-faf48d873aea)

Refreshed the graph immediately, and the chosen user shows up as T0 even before analysis runs:

![updated](https://github.com/SpecterOps/BloodHound/assets/24904109/921fe9a1-2260-4504-983a-68dea8137aa5)

Now to test removal, first I started off with picking SteveDraper00002 which is already marked as a T0:

![before](https://github.com/SpecterOps/BloodHound/assets/24904109/133385cc-7b0d-4f60-b0c3-592be78e574a)

Hit the endpoint and removed this selector:

![remove post](https://github.com/SpecterOps/BloodHound/assets/24904109/673e5efd-ca4d-423d-8450-68159a18080f)

Immediately querying via the UI shows the node has been removed from T0:

![after](https://github.com/SpecterOps/BloodHound/assets/24904109/4d3d5623-50de-4f66-841b-9d083b798de7)

## Types of changes

-   [ ] Chore (a change that does not modify the application functionality)
-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

-   [ ] Documentation updates are needed, and have been made accordingly.
-   [x] I have added and/or updated tests to cover my changes.
-   [x] All new and existing tests passed.
-   [ ] My changes include a database migration.

2023-11-17 15:37 UTC, elikmiller commented on cmd/api/src/api/v2/agi.go
> +			}
I'm not sure if you are soliciting feedback on this MR yet however I think we should simplify this logic to just apply or remove `assetGroup.Tag` based on if the selector is being created or deleted. There may be a future where we introduce additional asset groups in which case defaulting to `model.OwnedAssetGroupTag` is not the desired behavior.

2023-11-17 15:38 UTC, elikmiller commented on cmd/api/src/api/v2/agi.go
> +					}).Update(nodeProperties); err != nil {
We also want to not necessarily overwrite all existing tags. If a node is already a part of tier zero, and we are adding it to owned via a selector, we don't want to overwrite the existing tier zero tag.

2023-11-17 21:06 UTC, elikmiller requested changes
I added a node to an asset group via a selector and saw that the asset group label was appended to the "system_tags" property of that node. However, when removing the same selector I noted that the node was still tagged as being part of that asset group.

2023-11-17 22:16 UTC, codydbentley approved these changes
I'm not super familiar with asset tagging logic, but I don't see anything that stands out codewise. As long as the other issues are resolved, lgtm

2023-11-20 21:38 UTC, elikmiller requested changes

2023-11-20 21:38 UTC, elikmiller commented on cmd/api/src/api/v2/agi.go
> +			}
I notice that any modification to an asset group causes all members of other asset groups to disappear. I think only the nodes associated with a selector need to be modified/tagged.

2023-11-29 19:56 UTC, rvazarkar approved these changes

2023-11-29 23:19 UTC, merged