Bed 4069
SpecterOps/BloodHound pull request #383
Opened 2024-02-02 17:05 UTC by benwaples

## Description
Adds `Partially Completed` status for analysis to reflect when parts of analysis fail and others do not. This means that analysis can complete 1 of 3 ways:
1. `Complete` - All of analysis completes successfully
2. `Partially Complete` - Some parts of analysis failed, however at least one was successful.
3. `Failed` - All parts of analysis failed.

## Motivation and Context
When customers go to see the status of collection and analysis, they are only advised `Complete` or `Failed`.  This is based on the complete analysis finishing without any warnings or errors. Because some of analysis can fail but some data is still processed, a status of Partially Completed with additional logging should help trouble shoot the problem.

## How Has This Been Tested?
Manual testing errors happening at each step of analysis independently and collectively.

## Types of changes
-   [ ] Chore (a change that does not modify the application functionality)
-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
-   [ ] Documentation updates are needed, and have been made accordingly.
-   [ ] I have added and/or updated tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] My changes include a database migration.

2024-02-02 22:37 UTC, benwaples commented on cmd/api/src/daemons/datapipe/analysis.go
> +	ErrAnalysisPartiallyCompleted = errors.New("analysis partially failed")
thats a great point! Ill fix that

2024-02-03 00:06 UTC, computator requested changes
This looks good overall, but I added some feedback on the implementation

2024-02-03 00:06 UTC, computator commented on cmd/api/src/daemons/datapipe/analysis.go
> +		collectedErrors = errors.Join(collectedErrors, fmt.Errorf("fix well known node types failed: %w", err))
This is not the intended usage of `errors.Join()`. It is not like `append()` and repeatedly calling it to add a new error will not end up with a list, but rather somewhat of a nested tree structure. `errors.Join()` is intended to be called once with the final list of errors. (See: https://github.com/golang/go/issues/60209 and implementation in https://cs.opensource.google/go/go/+/refs/tags/go1.21.6:src/errors/join.go;l=15)

This also applies to many of the other uses throughout the PR

2024-02-03 00:19 UTC, benwaples commented on cmd/api/src/daemons/datapipe/jobs.go
> +				log.Errorf("Failed updating file upload job %d to failed status: %v", job.ID, err)
ahh good catch! I can update that. Thanks

2024-02-03 00:35 UTC, computator commented on cmd/api/src/daemons/datapipe/analysis.go
> +		collectedErrors = errors.Join(collectedErrors, fmt.Errorf("fix well known node types failed: %w", err))
We discussed this in Slack, but my suggestion is to `append()` to a slice of errors and then you can use `errors.Join()` to combine them all one time at the end.

2024-02-03 00:45 UTC, computator approved these changes

2024-02-05 20:56 UTC, merged