fix: plumb context into client db methods
SpecterOps/BloodHound pull request #450
Opened 2024-02-29 14:08 UTC by mistahj67

## Description

Plumb context into gorm client db methods
https://gorm.io/docs/context.html#Context-Timeout

I also noticed there was a number of unused db methods related to the asset-groups so I removed those to keep things nice and clean. (I didn't check the rest of the methods, but I do think it would be beneficial to give them all a quick audit)

## Motivation and Context

Currently as it stands any endpoints that rely on purely gorm do not respect `request.Context` and as such timeouts are not respected either. While we want to eventually get to the removal of the gorm dependency altogether, that is a long way and a lot of effort away and this I think this approach would give us that much room to maneuver while we get there.

## How Has This Been Tested?

Using a rest client and the prefer header
Add a sleep inside of the handler
Look for the `500 request timed out` after exceeding the timeout. (Note: the request will take as long as the sleep is set, it's not tied to the prefer header)

## Types of changes

-   [ ] Chore (a change that does not modify the application functionality)
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

-   [ ] Documentation updates are needed, and have been made accordingly.
-   [x] I have added and/or updated tests to cover my changes.
-   [x] All new and existing tests passed.
-   [ ] My changes include a database migration.

2024-03-01 20:40 UTC, juggernot325 approved these changes

2024-03-01 21:49 UTC, zinic commented on cmd/api/src/database/auth.go
> +func (s contextInitializer) InitContextFromToken(_ context.Context, authToken model.AuthToken) (auth.Context, error) {
Why not just plumb this into the `GetUser` call below?

2024-03-01 21:49 UTC, zinic requested changes
Have a comment around `InitContextFromToken` that I'd like addressed before approval.

2024-03-04 18:03 UTC, zinic commented on cmd/api/src/database/auth.go
> +func (s contextInitializer) InitContextFromToken(_ context.Context, authToken model.AuthToken) (auth.Context, error) {
Got it. Solid.

2024-03-04 18:03 UTC, zinic approved these changes
LGTM. Pull!

2024-03-04 18:04 UTC, merged