docs: windows installation note
SpecterOps/BloodHound pull request #650
Opened 2024-06-11 09:07 UTC by JonasBK

## Description

Add note about installing BHCE on Windows.

## Motivation and Context

Ticket: BED-4453

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

-   [x] Chore (a change that does not modify the application functionality)
-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

-   [x] Documentation updates are needed, and have been made accordingly.
-   [ ] I have added and/or updated tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] My changes include a database migration.

2024-06-11 15:40 UTC, StephenHinck requested changes

2024-06-11 15:40 UTC, StephenHinck commented on README.md
> -  3. Locate the randomly generated password in the terminal output of Docker Compose
Looks like numbering got goofed in the changes. If you wouldn't mind confirming and then it looks good!

2024-06-12 10:07 UTC, JonasBK commented
@StephenHinck good catch. Now fixed.

2024-06-12 15:22 UTC, StephenHinck approved these changes

2024-06-12 15:22 UTC, merged