draft: BED-4611: Citrix CanRDP Post Processing
SpecterOps/BloodHound pull request #818
Opened 2024-08-28 14:56 UTC by brandonshearin

## Description

*Describe your changes in detail*

## Motivation and Context

This PR addresses: [GitHub issue or Jira ticket number]

*Why is this change required? What problem does it solve?*

## How Has This Been Tested?

*Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to
see how your change affects other areas of the code, etc.*

## Screenshots (optional):

## Types of changes

- Chore (a change that does not modify the application functionality)
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)
- Database Migrations

## Checklist:

- [ ] I have met the contributing prerequisites
  - Assigned myself to this PR
  - Added the appropriate labels
  - Associated an issue: https://github.com/SpecterOps/BloodHound/issues/672
  - Read the Contributing guide: https://github.com/SpecterOps/BloodHound/wiki/Contributing
- [ ] I have ensured that related documentation is up-to-date
  - Open API docs
  - Code comments (GoDocs / JSDocs)
- [ ] I have followed proper test practices
  - Added/updated tests to cover my changes
  - All new and existing tests passed

2024-09-04 20:12 UTC, mistahj67 commented on packages/go/analysis/ad/post.go
> +		if directAccessUsersGroup, err := FetchComputerLocalGroupByName(tx, computer, "Direct Access Users"); err != nil {
We discussed via zoom some cleanup opportunities but including this in review!

2024-09-04 20:31 UTC, StephenHinck commented on packages/go/analysis/ad/post.go
> +		query.And(
If so, you'd likely want LocalGroup, rather than Group (the former is for Local Groups specifically, while the latter is for AD groups)

2024-09-05 22:20 UTC, maffkipp commented on cmd/api/src/database/migration/migrations/v5.16.0.sql
> +VALUES (3, 'analysis.citrix_rdp_support', 'Citrix RDP Support', 'This configuration parameter toggles Citrix support during post-processing. When on, CanRDP edges will come from the `Direct Access Us
The description here should be updated with the new copy: This configuration parameter toggles Citrix support during post-processing. When enabled, computers identified with a 'Direct Access Users' local group will assume that Citrix is installed and CanRDP edges will require membership of both 'Direct Access Users' and 'Remote Desktop Users' local groups on the computer.

2024-09-05 22:20 UTC, maffkipp commented on cmd/api/src/model/appcfg/parameter.go
> +	CitrixRDPSupportDescription = "This configuration parameter toggles Citrix support during post-processing. When on, CanRDP edges will come from the `Direct Access Users` group instead of the builtin
Same copy change as above

2024-09-09 15:31 UTC, mistahj67 requested changes
Migration needs to be fixed, otherwise code looks good

2024-09-09 15:31 UTC, mistahj67 commented on cmd/api/src/database/migration/migrations/v5.16.0.sql
> +'This configuration parameter toggles Citrix support during post-processing. When enabled, computers identified with a ''Direct Access Users''',
This needs to be updated with the new copy

2024-09-09 15:31 UTC, mistahj67 commented on cmd/api/src/database/migration/migrations/v5.16.0.sql
> +'This configuration parameter toggles Citrix support during post-processing. When enabled, computers identified with a ''Direct Access Users''',
Additionally the INSERT statement is missing and we don't want to insert a specified id of 3 but rely on the autoincr sequence

2024-09-09 17:16 UTC, mistahj67 approved these changes
Removing my requested changes from blocking this. Code looks good to me, nice job! I don't have the ability to locally confirm edges are being properly created so if you have time and can verify that with good example data, then I say ship it! 🚀

2024-09-12 20:05 UTC, merged