esc9b and esc10b abuse info improvement
SpecterOps/BloodHound pull request #845
Opened 2024-09-09 15:00 UTC by JonasBK

## Description

ESC9b and ESC10b require the attacker to modify the SPN of a victim account. Add that step to the abuse steps for those edges.

## Motivation and Context

This PR addresses: BED-4804

## How Has This Been Tested?

Verified that all the abuse sections looks good.

## Screenshots (optional):

![image](https://github.com/user-attachments/assets/381d93a3-bcb3-493d-a5fa-796f02f35fd4)

## Types of changes

- Chore (a change that does not modify the application functionality)

## Checklist:

- [x] I have met the contributing prerequisites
  - Assigned myself to this PR
  - Added the appropriate labels
  - Associated an issue: https://github.com/SpecterOps/BloodHound/issues/672
  - Read the Contributing guide: https://github.com/SpecterOps/BloodHound/wiki/Contributing
- [x] I have ensured that related documentation is up-to-date
  - Open API docs
  - Code comments (GoDocs / JSDocs)
- [x] I have followed proper test practices
  - Added/updated tests to cover my changes
  - All new and existing tests passed

2024-09-18 15:48 UTC, juggernot325 requested changes
Small typos should be fixed up since we're here. Then this is good to go!

2024-09-18 15:48 UTC, juggernot325 commented on packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC10b/WindowsAbuse.tsx
> +                to it’s previous values using Certipy and PowerView:
Small typo: `it's` should be `its`.

2024-09-19 08:25 UTC, JonasBK commented on packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC10b/WindowsAbuse.tsx
> +                to it’s previous values using Certipy and PowerView:
Good call 👍

2024-09-19 14:55 UTC, juggernot325 commented on packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC10b/LinuxAbuse.tsx
> +                to it's previous values using Certipy and ldapmodify:
Sorry! I thought I marked each of these but I guess I forgot to save them? There's a few more instances of incorrect `it's`.

2024-09-19 15:18 UTC, merged