Bed 4767
SpecterOps/BloodHound pull request #898
Opened 2024-10-04 23:14 UTC by mistahj67

## Description

**Note: This shouldn't be merged into BED-4768 and should wait until the following are merged:

- https://github.com/SpecterOps/BloodHound/pull/896
- https://github.com/SpecterOps/BloodHound/pull/894
- https://github.com/SpecterOps/BloodHound/pull/897

It was just selected as the base for easier PR review.**

Add callback handler for OIDC

## Motivation and Context

This PR addresses: BED-4767

*Why is this change required? What problem does it solve?*
In order to support OIDC we need to have a generic callback handler

## How Has This Been Tested?

This is used in conjunction with Authentik locally to verify proper callback handling occurred.

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have met the contributing prerequisites
  - Assigned myself to this PR
  - Added the appropriate labels
  - Associated an issue: https://github.com/SpecterOps/BloodHound/issues/672
  - Read the Contributing guide: https://github.com/SpecterOps/BloodHound/wiki/Contributing
- [x] I have ensured that related documentation is up-to-date
  - Open API docs
  - Code comments (GoDocs / JSDocs)
- [x] I have followed proper test practices
  - Added/updated tests to cover my changes
  - All new and existing tests passed

2024-10-04 23:15 UTC, mistahj67 commented on cmd/api/src/api/auth.go
> +			break
This must be done once user table is properly migrated / updated to handle either a generic sso_provider_id or a second oidc_provider_id table @mvlipka

2024-10-04 23:17 UTC, mistahj67 commented on cmd/api/src/model/sso_provider.go
> +	Type SessionAuthProvider `json:"type"`
This likely needs to be updated to whatever was reflected in https://github.com/SpecterOps/BloodHound/pull/896

2024-10-24 20:06 UTC, mistahj67 commented on cmd/api/src/api/auth.go
> +			break
Will need to be updated with the patch user PR

2024-10-24 21:14 UTC, ddlees requested changes

2024-10-24 21:14 UTC, ddlees commented on cmd/api/src/api/saml/saml.go
> +			}
Since `getSAMLUserPrincipalNameFromAssertion` now only returns one type of error you can simplify this error handling logic.

2024-10-24 21:14 UTC, ddlees commented on cmd/api/src/api/v2/auth/sso.go
> +			api.WriteErrorResponse(request.Context(), api.BuildErrorResponse(http.StatusNotFound, api.ErrorResponseDetailsResourceNotFound, request), response)
Consider `501 - Not Implemented` instead

2024-10-24 21:14 UTC, ddlees commented on cmd/api/src/api/v2/auth/sso.go
> +			api.WriteErrorResponse(request.Context(), api.BuildErrorResponse(http.StatusNotFound, api.ErrorResponseDetailsResourceNotFound, request), response)
Consider `501 - Not implemented` instead

2024-10-24 21:14 UTC, ddlees commented on packages/go/crypto/tls.go
> +	if keyBlock == nil {
:bow: Thank you

2024-10-25 14:29 UTC, ddlees approved these changes

2024-10-25 20:26 UTC, merged