BED-4934: Posture page feature flag
SpecterOps/BloodHound pull request #902
Opened 2024-10-11 16:33 UTC by maffkipp

## Description
Adds a new feature flag to the current migration file with the key `updated_posture_page`. The flag should initially be set to false and should be non user-updatable.

## Motivation and Context
This feature flag will be used for toggling to the new posture page during development.

This PR addresses: [BED-4934]

## How Has This Been Tested?
Confirmed migration runs on startup and creates the new flag with the expected settings and initial value.

## Screenshots (optional):

## Types of changes
- Chore (a change that does not modify the application functionality)
- Database Migrations

## Checklist:
- [x] I have met the contributing prerequisites
  - Assigned myself to this PR
  - Added the appropriate labels
  - Associated an issue: https://github.com/SpecterOps/BloodHound/issues/672
  - Read the Contributing guide: https://github.com/SpecterOps/BloodHound/wiki/Contributing
- [x] I have ensured that related documentation is up-to-date
  - Open API docs
  - Code comments (GoDocs / JSDocs)
- [x] I have followed proper test practices
  - Added/updated tests to cover my changes
  - All new and existing tests passed

2024-10-11 20:50 UTC, specter-flq commented
Makes sense imo, but will defer to the veterans for approval.

2024-10-14 17:41 UTC, byt3exec requested changes
Makes sense for DM.sql

2024-10-16 19:15 UTC, benwaples approved these changes

2024-10-16 19:17 UTC, elikmiller approved these changes

2024-10-16 19:18 UTC, elikmiller commented
> Makes sense for DM.sql

@byt3exec perhaps you meant to comment on a different PR?

2024-10-16 22:02 UTC, merged