BED-4817: Update API types for posture page
SpecterOps/BloodHound pull request #973
Opened 2024-11-21 20:26 UTC by maffkipp

## Description
Updates a few types in our javascript API client to account for changes to the spec for the endpoint we are using to feed our new posture page charts.

The current openAPI spec for that endpoint can be found here: https://github.com/SpecterOps/BloodHound/compare/main...posture-api-spec

## Motivation and Context

This PR addresses: [BED-4817]

## How Has This Been Tested?

## Screenshots (optional):

## Types of changes
- Chore (a change that does not modify the application functionality)

## Checklist:
- [x] I have met the contributing prerequisites
  - Assigned myself to this PR
  - Added the appropriate labels
  - Associated an issue: https://github.com/SpecterOps/BloodHound/issues/672
  - Read the Contributing guide: https://github.com/SpecterOps/BloodHound/wiki/Contributing
- [x] I have ensured that related documentation is up-to-date
  - Open API docs
  - Code comments (GoDocs / JSDocs)
- [x] I have followed proper test practices
  - Added/updated tests to cover my changes
  - All new and existing tests passed

2024-11-22 00:14 UTC, elikmiller approved these changes

2024-11-22 15:57 UTC, elikmiller approved these changes

2024-11-23 02:13 UTC, elikmiller commented
I can't comment there because it wasn't changed in this PR but we also need to update the other endpoint to be 
`/api/v2/domains/{environment_id}/finding-trends`

2024-11-23 02:14 UTC, elikmiller requested changes

2024-11-23 02:14 UTC, elikmiller commented on packages/javascript/js-client-library/src/client.ts
> +            `/api/v2/${environmentId}/posture-history/${dataType}`,
is `/api/v2/domains/{environment_id}/posture-history/{data_type}` according to the spec!

2024-11-26 00:05 UTC, elikmiller approved these changes

2024-11-26 15:33 UTC, sircodemane approved these changes

2024-11-27 19:03 UTC, merged