BED-5060: Prevent user from changing their own role/auth
SpecterOps/BloodHound pull request #984
Opened 2024-11-26 21:36 UTC by wes-mil

## Description

Prevent a user from updating their own role or auth method within user configuration.

Also addresses two bugs discovered while addressing ticket:
- An admin user could accidentally delete a user's password while adjusting their authentication method
- GetAuthSecret didn't return ERRNOTFOUND while attempting to get an auth secret by ID

## Motivation and Context

This PR addresses: BED_5060

*Why is this change required? What problem does it solve?*

An admin user could change their own role to a role that is not privileged or change their own authentication method to something else. While this could be intentional, it largely caused issues with misconfigured SSO providers or accidental role changing. Effectively preventing that user from authenticating or having privilege. In the worst case, this could occur have occured while there was only a single admin user in the account.

## How Has This Been Tested?

An admin user is created an then the user attempts to change their role through user configuration. On the UI these fields are now grayed out. Through the API, a PATCH request is made using an API token from an admin user attempting configure those fields. The API returns a 400 response now.

Test cases were added for the changes to database method UpdateUser.

## Screenshots (optional):

![image](https://github.com/user-attachments/assets/914c1863-649f-4fb2-8419-09794fd746fc)

![Screenshot from 2024-11-25 15-20-02](https://github.com/user-attachments/assets/7290a783-aeda-4cd1-b4b0-ff97a91f2503)

![Screenshot from 2024-11-25 15-24-01](https://github.com/user-attachments/assets/2d1c7e1d-5b56-4d77-8b58-2d2057b8cdc6)

## Types of changes

- Chore (a change that does not modify the application functionality)
- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have met the contributing prerequisites
  - Assigned myself to this PR
  - Added the appropriate labels
  - Associated an issue: https://github.com/SpecterOps/BloodHound/issues/672
  - Read the Contributing guide: https://github.com/SpecterOps/BloodHound/wiki/Contributing
- [x] I have ensured that related documentation is up-to-date
  - Open API docs
  - Code comments (GoDocs / JSDocs)
- [x] I have followed proper test practices
  - Added/updated tests to cover my changes
  - All new and existing tests passed

2024-11-26 23:20 UTC, mistahj67 requested changes
I think the disabled route is more apparent to the user but the ticket requests it not appear at all. Likely can verify with Ryan which we prefer!

2024-11-26 23:20 UTC, mistahj67 commented on cmd/api/src/api/error.go
> +	ErrorResponseUserSelfSSOChange                  = "user attempted to change own SSO"
```suggestion
	ErrorResponseUserSelfSSOChange                  = "user attempted to change own SSO Provider"
```

2024-11-26 23:20 UTC, mistahj67 commented on cmd/api/src/database/auth.go
> +
This feels a bit like we are swimming up stream. I'm hopeful we can find a smoother way if we pair!

2024-11-27 17:19 UTC, mistahj67 commented on cmd/api/src/database/auth.go
> +
After pairing, we opted for the more verbose but single pathway of calling the DeleteAuthSecret method to ensure audit logs are maintained

2024-12-03 00:26 UTC, mistahj67 approved these changes
Tested locally, code LGTM. I'd still snag another ✅ since we ended up pairing on this, particularly the db method choice.

2024-12-05 22:18 UTC, ALCooper12 commented
LGTM! Appreciate the explanations to my questions earlier!

2024-12-05 22:19 UTC, ALCooper12 approved these changes
LGTM! Appreciate the explanations to my questions earlier!

2024-12-06 16:27 UTC, merged